<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Générateur Lorem Ipsum</title>
</head>
<body>

<h1>Générateur de Texte Lorem Ipsum</h1>

<?php
$paragraphs = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat justo, venenatis nec imperdiet et, mattis id ipsum. Donec at hendrerit justo, id suscipit sem. Sed malesuada dapibus lectus, nec suscipit purus dictum vel. Duis sollicitudin vehicula odio, in dapibus metus cursus eget. Proin interdum justo vitae dolor commodo tempus. Sed vel volutpat ligula. Quisque tincidunt mauris in urna congue fringilla. Proin laoreet condimentum eros, eu vulputate tellus. Proin eleifend vulputate dictum. Mauris urna tortor, varius at odio quis, viverra accumsan nisl. Sed pharetra ante urna, et varius nisl porta quis. Nunc quis porta ante. Nam in dignissim nisi.",
    "Donec consectetur porttitor nibh, eu ullamcorper neque aliquet vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam sollicitudin consectetur purus, id laoreet ipsum vehicula ut. Nullam in diam ipsum. Nullam accumsan vestibulum ipsum, sit amet aliquet lectus sollicitudin non. Quisque lorem libero, ultricies vitae auctor eget, semper eget lectus. Fusce vel leo tincidunt nulla sollicitudin imperdiet. Fusce laoreet non elit sit amet venenatis. Phasellus rutrum, sem vel pellentesque porta, felis orci volutpat urna, id blandit eros arcu ac dui. Ut bibendum elit lacus, ut elementum ex auctor eget. Nullam aliquam enim sed nisl tincidunt volutpat.",
    "Nunc pellentesque, ipsum nec sodales suscipit, diam odio congue sapien, sed semper velit purus vel sem. Duis bibendum lacus eget diam consectetur, at pharetra sapien tempus. Nullam in ex imperdiet, ultrices tortor a, vehicula velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin felis tellus, consequat in euismod sed, efficitur vitae enim. In eros lorem, tempus vel felis non, posuere ultricies sapien. Sed id justo semper, gravida ipsum at, mollis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mattis nibh et fermentum blandit. Nam cursus posuere quam vel porta. Donec mattis mollis mi eu posuere. Aenean laoreet, neque sed ultrices scelerisque, neque libero iaculis sem, eget porttitor justo augue ac dolor.",
    "Aenean eu enim sed ex rutrum maximus non sit amet arcu. Mauris sit amet aliquet nulla, sit amet aliquam urna. Maecenas venenatis lectus eget mauris tristique, ac pulvinar justo rutrum. Quisque ut ipsum eget turpis elementum interdum sit amet vel erat. Cras lacinia odio sit amet dignissim hendrerit. Praesent et placerat orci, a sollicitudin neque. Proin sem libero, rhoncus quis dui ut, accumsan consequat odio. Donec facilisis nulla sit amet tellus elementum facilisis. Sed maximus orci sit amet ipsum sagittis, vitae mollis ante aliquam. Maecenas vitae feugiat quam, et condimentum metus. Morbi malesuada enim magna, id mattis nunc laoreet in. Nunc a libero a elit finibus euismod ac a mauris. Donec auctor vehicula arcu quis gravida. Suspendisse id felis quam. Nam porta fringilla efficitur. Aliquam erat volutpat.",
    "Suspendisse potenti. Praesent molestie iaculis interdum. Sed egestas condimentum nunc, id pharetra magna rutrum ut. Pellentesque lorem libero, facilisis vitae enim sed, sollicitudin interdum tellus. Curabitur leo nulla, tincidunt eu eros eu, convallis placerat nisl. Sed consectetur turpis a pretium euismod. Quisque dictum enim non tortor suscipit cursus.",
    "Nullam ac tincidunt tortor. Nunc suscipit non nulla ut tristique. Nam sodales hendrerit odio sed luctus. Phasellus at nisl augue. Duis sit amet velit sit amet orci tincidunt facilisis. Morbi a purus at elit scelerisque congue. Aliquam eget leo rhoncus, condimentum felis in, mollis sapien. Phasellus tempor egestas auctor. Sed vel porta risus, vel rhoncus purus. Nulla cursus euismod pharetra. Fusce condimentum dignissim sollicitudin. Cras ornare, mi eu cursus euismod, urna nunc lacinia mauris, non lobortis felis magna vitae nisi. Etiam consequat neque nec ipsum laoreet volutpat quis semper risus. Vivamus vitae elementum lectus.",
    "Sed tincidunt ipsum augue, a feugiat ex pellentesque non. Donec tempor justo aliquet accumsan lacinia. Sed eget diam varius, dictum metus convallis, malesuada ipsum. Praesent orci elit, vehicula vel pulvinar et, viverra ultricies magna. Morbi id justo nec urna eleifend auctor. Curabitur commodo, augue non vulputate ultricies, neque arcu vulputate turpis, at mattis nulla velit id metus. Phasellus eget quam consequat ante egestas tempus porta viverra mi.",
    "Proin sit amet mattis augue. Pellentesque posuere massa ac consequat placerat. Suspendisse luctus arcu eu justo faucibus, nec egestas metus auctor. Maecenas nisi ligula, euismod et faucibus quis, sollicitudin quis metus. Quisque eu faucibus ipsum. Mauris ut nunc diam. Quisque dictum enim ac nisi fermentum, a suscipit urna condimentum. Nulla in ullamcorper odio. Maecenas maximus egestas mi. Suspendisse consequat urna lacus.",
    "Cras tempor sed neque sed aliquet. Donec blandit fringilla lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer eget ligula interdum, mattis nunc non, venenatis tortor. Donec commodo lacus et felis ultrices, a placerat erat vestibulum. Donec in ante fringilla, ullamcorper lacus vitae, porta justo. Donec et varius velit. Cras et blandit neque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Proin blandit pellentesque lorem at vulputate. Quisque nisi neque, consectetur et ante convallis, efficitur molestie nunc. Praesent non turpis gravida, mattis dui id, scelerisque dui. Nullam scelerisque, mauris non sagittis accumsan, tortor felis ornare ipsum, ac venenatis nisi ante vestibulum mi.",
    "Quisque consequat risus augue, ac porttitor metus iaculis sit amet. In hac habitasse platea dictumst. Fusce eleifend velit in ornare viverra. Duis quis nisi ornare, malesuada nibh sit amet, mattis sapien. Proin molestie nisl felis, eget tempus dolor egestas quis. Proin ultricies posuere posuere. Morbi sit amet felis nibh. Sed nec sem at nibh consequat facilisis. Maecenas aliquet nisl vitae felis pretium, non posuere est dapibus. Nullam sit amet mauris risus. Pellentesque vel hendrerit lacus. Aliquam aliquam risus eget interdum vehicula. Quisque nec commodo magna. Nullam at urna quis ex pulvinar aliquet. Mauris finibus scelerisque tincidunt. Sed at turpis vitae nibh faucibus congue hendrerit quis ante.",
    "Vivamus a purus nibh. Vivamus id neque ac augue congue euismod id sit amet orci. Etiam id porttitor ipsum, vel efficitur elit. Vestibulum et finibus nibh. Suspendisse dictum bibendum est ut lobortis. Vestibulum consectetur, lorem nec auctor sodales, tellus nibh tempor velit, quis consequat nibh arcu nec mi. Nunc mollis nulla lectus, vitae condimentum nisi rhoncus ut. Sed venenatis iaculis ex, sit amet pharetra ex condimentum in. Nunc auctor mi non odio pharetra efficitur. Aliquam in ligula at lorem mollis facilisis. Phasellus in egestas erat. Integer a urna imperdiet, feugiat nibh sit amet, vulputate felis. Fusce egestas scelerisque dui nec egestas. Cras ligula diam, lobortis finibus nisi sed, imperdiet egestas est.",
    "Aliquam pellentesque fringilla nunc at vehicula. Aliquam varius maximus varius. Etiam vehicula sit amet tortor ac fringilla. Cras quis quam et eros molestie fermentum sed a felis. Nunc dignissim porttitor rutrum. Vestibulum imperdiet tellus a quam scelerisque consequat. Integer nibh lacus, vulputate non dignissim vel, congue nec nibh. Duis ultricies magna id eros rhoncus gravida. In blandit rhoncus tempor. Nam aliquam semper pharetra. Mauris porta suscipit ante, at feugiat felis faucibus aliquet. Proin suscipit convallis tortor et consequat. Etiam aliquam massa sit amet blandit tempor. Cras ornare convallis lacinia. Nam non interdum dui. Aenean sed turpis scelerisque, venenatis metus rhoncus, rutrum urna.",
    "Aliquam euismod erat sit amet consequat pharetra. Maecenas elit leo, elementum in pulvinar non, feugiat ut enim. Suspendisse potenti. Sed tempor turpis ut semper luctus. Ut non placerat dui, facilisis posuere leo. Suspendisse vitae commodo dui, non cursus nunc. Etiam ac pretium justo. Sed at nibh vitae ligula dictum posuere nec eget magna. Etiam molestie risus a fermentum luctus. Phasellus dignissim volutpat viverra. Curabitur luctus odio quis elit vulputate, ut suscipit felis venenatis. Nullam sed nibh dui.",
    "Phasellus nisi eros, lacinia ac vestibulum eget, viverra eu nibh. Nulla vitae sem ac felis bibendum consequat ut eu purus. Maecenas in urna tempus, porta erat ac, porttitor risus. Maecenas facilisis id enim vitae gravida. In ac tristique ante, eget pellentesque diam. Maecenas sed diam a velit consectetur finibus. Aliquam blandit velit ac nunc elementum, sit amet efficitur nulla vestibulum. Praesent erat libero, pretium id gravida sit amet, elementum nec erat. Etiam sollicitudin ac eros nec vehicula. Integer purus neque, elementum quis bibendum at, pharetra sed arcu.",
    "Proin efficitur ac felis eu finibus. Mauris dapibus in quam vestibulum aliquam. Curabitur at quam id mauris commodo laoreet. Aenean quis purus euismod, rhoncus neque sed, aliquam nulla. In massa ipsum, euismod ut nulla nec, imperdiet semper dolor. Mauris egestas gravida lectus, quis placerat libero faucibus vel. Duis iaculis eget risus ut bibendum. Morbi sit amet lorem metus. Sed quis elementum mauris. Nullam sodales dapibus metus, non pellentesque dolor mattis at. Curabitur lacinia tristique quam a euismod. Donec nec orci leo. Nunc id nulla volutpat, rutrum nunc ut, blandit dolor. Sed commodo, erat eu euismod porttitor, nunc massa vestibulum enim, aliquet dignissim eros mi id leo. Donec ultricies tempor libero. Vestibulum consequat congue massa.",
    "Phasellus non neque in ipsum faucibus aliquam at et erat. Vestibulum tristique dolor venenatis urna auctor imperdiet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean quam mauris, condimentum et tempus vitae, hendrerit at urna. Donec mauris dui, placerat sed bibendum in, porttitor quis arcu. Vivamus non nunc orci. Ut vitae odio ut risus pellentesque tristique. Praesent at porttitor neque. Suspendisse felis felis, cursus id eleifend in, fermentum nec justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi blandit nisl ut nisl condimentum, et bibendum lorem finibus. Suspendisse potenti. Maecenas quis semper erat. Aenean id pellentesque nulla, sed facilisis velit. Donec quis purus pulvinar, vehicula augue nec, blandit turpis. Duis viverra dignissim urna id pretium.",
    "Morbi porta scelerisque elit. Mauris sit amet molestie augue, nec imperdiet ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque ut augue ex. Etiam et maximus lectus. Nam et dictum augue. Vivamus quis turpis sed enim cursus vehicula at quis felis. Phasellus et luctus velit, a luctus leo. Nam volutpat, mi ac porttitor consectetur, eros urna vulputate ipsum, ac mollis dui purus in ligula. Proin pellentesque tellus rutrum purus pretium bibendum. Nulla a elit et quam convallis lacinia. Maecenas id elementum ipsum. Fusce laoreet molestie dictum. Pellentesque est nunc, scelerisque quis gravida ac, iaculis molestie urna.",
    "Ut sagittis dolor nec est dapibus, sit amet hendrerit nunc sodales. Nam eget mauris lobortis, accumsan risus eu, placerat leo. Quisque sodales sed purus at rhoncus. Vestibulum convallis ultricies felis lacinia porttitor. Phasellus sodales, turpis eget viverra sollicitudin, orci nibh dictum quam, a accumsan metus urna nec nisi. Aliquam commodo enim et iaculis malesuada. Nunc at finibus libero, in vulputate arcu.",
    "Nunc eu lacus in augue iaculis commodo sit amet venenatis erat. Suspendisse rutrum pellentesque nunc, eu finibus sem posuere venenatis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean blandit, enim vel suscipit aliquam, libero felis blandit eros, ut blandit augue erat a nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis pharetra est id augue pretium, ac efficitur tellus porta. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.",
    "Nam porta sem eget lectus semper, vitae faucibus metus tempus. Aliquam maximus ligula a hendrerit scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque finibus libero nulla, eu tincidunt ligula tristique et. Curabitur ornare dui id risus condimentum maximus. Fusce et quam a tortor pellentesque ultrices. Nam urna enim, egestas at eros in, fermentum imperdiet leo.",
    "Integer nec ligula nec est sodales rutrum eu et augue. Duis interdum scelerisque aliquet. Proin ac sagittis nibh, ac aliquam quam. Maecenas suscipit massa eu enim venenatis, ut malesuada dolor tempus. Sed dignissim vestibulum luctus. Sed ultrices neque vitae massa congue, et condimentum turpis fermentum. Aenean vulputate sit amet quam eleifend sagittis.",
    "Etiam in elementum sapien. Sed nisl nibh, feugiat et velit bibendum, cursus aliquet neque. Nullam interdum a nibh id tincidunt. Fusce vel ornare risus, id porta quam. Integer sed posuere lacus. Donec sodales convallis mi, egestas feugiat libero vehicula a. In viverra bibendum mi vitae rhoncus. Maecenas nibh nibh, dapibus in nibh vel, mattis faucibus turpis. Quisque molestie lorem et nunc dictum, a aliquam mi commodo. Suspendisse eleifend felis condimentum nunc tincidunt, ac tincidunt nisl porta. Sed sodales elit in mi ultrices laoreet. Fusce in pretium nisl. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "Aenean rutrum vitae sapien sed convallis. Sed id velit ipsum. Sed in nisl quis arcu ullamcorper pulvinar. Nulla in vulputate magna. Etiam at auctor mi. Aenean bibendum ex et pretium convallis. Proin malesuada feugiat blandit. Donec gravida ut erat vel feugiat. Ut vestibulum felis lacus, vel commodo nisl faucibus sed. Integer mattis, nisi vestibulum dignissim porta, metus nunc pretium mauris, in maximus libero sem quis sem. Fusce accumsan est sapien, a volutpat ipsum rutrum ullamcorper. Cras ut blandit ligula. Sed ultrices erat quis diam maximus volutpat. Morbi magna ligula, ultricies eu facilisis vel, tempus non tortor. Ut tortor diam, pellentesque non porta eget, condimentum vel lectus.",
    "Sed eu risus convallis, elementum purus sit amet, molestie magna. Fusce id urna ac eros egestas dictum non et massa. Nullam sed fringilla ante. Proin lacinia porttitor ex sit amet laoreet. Duis tristique mattis faucibus. Cras suscipit ac nisi sit amet mattis. Aliquam erat volutpat. Duis lacinia nunc in tortor porta, eget maximus sapien suscipit. Nam varius tempus risus sed convallis.",
    "Sed vitae mi luctus, ornare diam sed, blandit ligula. Cras sit amet dui eu diam rhoncus cursus in sed metus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec augue erat, feugiat sit amet venenatis sit amet, tempus vitae est. Ut ultrices in augue rutrum ornare. Nunc quis accumsan nunc. Praesent erat orci, porta vitae rutrum et, ultricies at lorem. Proin vestibulum elementum pulvinar. Nullam risus diam, condimentum vel tellus non, venenatis gravida augue. Nullam vel turpis a metus feugiat gravida ultrices ullamcorper enim. Pellentesque lectus sem, interdum quis elementum sed, consequat tincidunt est. Pellentesque blandit non leo non bibendum. Morbi eu justo sed erat commodo ultrices.",
    "Phasellus tellus arcu, condimentum eget volutpat vitae, pulvinar vitae purus. Morbi at lorem hendrerit, volutpat diam id, blandit nisi. Curabitur mollis porta purus, at fringilla nibh lacinia et. Vivamus nec justo justo. Aliquam ut sapien metus. Sed magna magna, bibendum a condimentum ac, placerat non urna. Nullam non sodales dolor, nec rhoncus metus. Aliquam volutpat tortor non urna bibendum, id blandit lacus dictum. Maecenas quis ante ut mauris scelerisque commodo. Aliquam vehicula in est id tempus. Cras dapibus venenatis leo id aliquet. Donec mollis augue quis neque vestibulum, ut sodales ex cursus. Praesent vitae facilisis est, in fringilla arcu. Mauris odio ligula, egestas eget hendrerit id, mattis sit amet urna. Nam lacinia dolor vitae neque ultrices aliquet.",
    "Vivamus sit amet pellentesque ante. Duis eu faucibus leo. Donec in vulputate ante. Vestibulum mauris augue, placerat at sem at, vulputate mollis tellus. Aenean urna quam, volutpat a nunc vitae, fringilla pulvinar ante. Donec eleifend, est vitae fringilla varius, leo leo tincidunt odio, ullamcorper dictum velit risus ultricies urna. Etiam dignissim a est eget molestie. Vivamus condimentum velit non sem imperdiet, eu aliquet nibh rutrum. Cras aliquam sapien eu justo volutpat, eu iaculis ex interdum. Sed bibendum, lorem in eleifend tempor, diam ligula ultrices sapien, non volutpat est tellus volutpat ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque vitae viverra enim. Donec eget magna neque. Donec venenatis sit amet nisi quis tempus. Pellentesque a est quam. Duis pretium diam justo, ut viverra orci pulvinar sed.",
    "Nam et eros ac leo suscipit maximus quis eget est. Quisque interdum ante in eros egestas, et finibus sem fermentum. Maecenas condimentum tortor dui, eu iaculis erat vulputate euismod. Nam vitae placerat nulla, vel ornare enim. Nam quis eleifend sem, sit amet laoreet mi. Mauris pretium leo id semper congue. Nunc nisi est, lobortis sit amet consequat vel, pharetra in velit. Ut pellentesque vitae lectus in varius. Integer sed consectetur risus, ut consectetur tellus.",
    "In viverra placerat pellentesque. Aliquam erat volutpat. Sed ut ipsum finibus, mattis elit ac, laoreet nisl. Donec egestas laoreet purus, non faucibus elit hendrerit quis. Duis suscipit ipsum vel dolor maximus, sed dapibus lectus consectetur. Ut id erat eu mauris iaculis tempus. Morbi metus erat, dictum maximus dapibus at, aliquet sagittis odio. Praesent tempor suscipit nunc scelerisque vehicula. Fusce scelerisque augue vitae augue eleifend, eu semper justo scelerisque. Nulla vestibulum magna a ante bibendum, pellentesque venenatis dolor dignissim. Nunc eu enim at dolor viverra vehicula convallis eleifend mauris. Duis a tortor nunc. Vestibulum quis condimentum nisi, ac egestas diam. Nullam pharetra id leo vel lobortis. Integer justo felis, bibendum consectetur interdum sit amet, hendrerit eu ipsum. Etiam volutpat id urna vitae pretium.",
    "Curabitur vitae tempus arcu, at posuere mi. Pellentesque eu lacinia urna. Donec accumsan id nibh eu vehicula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In nulla purus, scelerisque non turpis eget, dignissim sollicitudin ex. Nullam molestie elit vel ligula tristique, nec imperdiet erat tincidunt. In sit amet porttitor sem. Aenean finibus posuere dolor eget tempus. Suspendisse non mauris pharetra, dapibus lacus vitae, facilisis mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin quis pretium velit, non porta risus. Proin id pretium turpis, a ornare neque.",
];


$output = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {

    $count = isset($_POST['count']) ? (int)$_POST['count'] : 1;

    $count = min($count, count($paragraphs));

    for ($i = 0; $i < $count; $i++) {
        $output .= $paragraphs[$i] . "\n\n";
    }
}
?>

<form method="POST" action="Lorem-ipsum.php">
    <label for="count">Nombre de paragraphes :</label>
    <input type="number" name="count" id="count" min="1" max="30" value="1">
    <input type="submit" value="Générer">
</form>

<label for="result">Résultat :</label>
<textarea id="result" rows="10" cols="70" readonly><?php echo htmlspecialchars($output); ?></textarea>

</body>
</html>